//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsnafimEdirneServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsnafKayitt
    {
        public int Id { get; set; }
        public string VergiNo { get; set; }
        public string FirmaUnvan { get; set; }
    }
}
