//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsnafimEdirneServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsnafHesap
    {
        public int Id { get; set; }
        public string HesapAd { get; set; }
        public string Iban { get; set; }
        public Nullable<bool> Sil { get; set; }
    }
}
