//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsnafimEdirneServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esnaf
    {
        internal object min;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Esnaf()
        {
            this.HizmetSaat = new HashSet<HizmetSaat>();
            this.Kampanya = new HashSet<Kampanya>();
            this.Siparis = new HashSet<Siparis>();
            this.Urun = new HashSet<Urun>();
            this.UrunKategori = new HashSet<UrunKategori>();
        }
    
        public int Id { get; set; }
        public string FirmaUnvan { get; set; }
        public string VergiNo { get; set; }
        public string KisaAd { get; set; }
        public string Telefon { get; set; }
        public string EPosta { get; set; }
        public Nullable<int> HizmetKategoriID { get; set; }
        public Nullable<bool> KapidaKredi { get; set; }
        public Nullable<bool> KapidaNakit { get; set; }
        public Nullable<decimal> MinSiparis { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public string EPostaCheck { get; set; }
        public Nullable<int> IlceId { get; set; }
        public string Adres { get; set; }
        public string Sifre { get; set; }
        public string Token { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public Nullable<bool> Online { get; set; }
        public string FotoYol { get; set; }
        public Nullable<bool> EpostaOnay { get; set; }
        public Nullable<System.TimeSpan> HizmetBaslama1 { get; set; }
        public Nullable<System.TimeSpan> HizmetBitis1 { get; set; }
        public Nullable<bool> Hizmet1 { get; set; }
        public Nullable<System.TimeSpan> HizmetBaslama2 { get; set; }
        public Nullable<System.TimeSpan> HizmetBitis2 { get; set; }
        public Nullable<bool> Hizmet2 { get; set; }
        public Nullable<System.TimeSpan> HizmetBaslama3 { get; set; }
        public Nullable<System.TimeSpan> HizmetBitis3 { get; set; }
        public Nullable<bool> Hizmet3 { get; set; }
        public Nullable<System.TimeSpan> HizmetBaslama4 { get; set; }
        public Nullable<System.TimeSpan> HizmetBitis4 { get; set; }
        public Nullable<bool> Hizmet4 { get; set; }
        public Nullable<System.TimeSpan> HizmetBaslama5 { get; set; }
        public Nullable<System.TimeSpan> HizmetBitis5 { get; set; }
        public Nullable<bool> Hizmet5 { get; set; }
        public Nullable<System.TimeSpan> HizmetBaslama6 { get; set; }
        public Nullable<System.TimeSpan> HizmetBitis6 { get; set; }
        public Nullable<bool> Hizmet6 { get; set; }
        public Nullable<System.TimeSpan> HizmetBaslama7 { get; set; }
        public Nullable<System.TimeSpan> HizmetBitis7 { get; set; }
        public Nullable<bool> Hizmet7 { get; set; }
        public Nullable<int> TeslimatSuresi { get; set; }
    
        public virtual HizmetKategori HizmetKategori { get; set; }
        public virtual Ilce Ilce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HizmetSaat> HizmetSaat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kampanya> Kampanya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urun> Urun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunKategori> UrunKategori { get; set; }
    }
}
