//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsnafimEdirneServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HizmetSaat
    {
        public int Id { get; set; }
        public Nullable<int> EsnafId { get; set; }
        public Nullable<System.TimeSpan> SaatBaslama { get; set; }
        public Nullable<System.TimeSpan> SaatBitis { get; set; }
        public Nullable<bool> Acik { get; set; }
    
        public virtual Esnaf Esnaf { get; set; }
    }
}
