//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsnafimEdirneServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        public int Id { get; set; }
        public Nullable<int> SiparisId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<bool> Sil { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<int> EsnafId { get; set; }
        public Nullable<decimal> IndirimTutari { get; set; }
        public Nullable<decimal> IndirimliTutar { get; set; }
    
        public virtual Siparis Siparis { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
