//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsnafimEdirneServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.SiparisDetay = new HashSet<SiparisDetay>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Aciklama { get; set; }
        public string FotoYol { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> EsnafId { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> KdvId { get; set; }
        public Nullable<bool> Sil { get; set; }
        public Nullable<bool> Mevcut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
        public virtual UrunKategori UrunKategori { get; set; }
        public virtual Vergi Vergi { get; set; }
        public virtual Esnaf Esnaf { get; set; }
    }
}
